---
- name: "Backup - Minecraft - Stop"
  containers.podman.podman_container:
    name: minecraft
    state: stopped

- name: "Backup - Minecraft - Save"
  community.general.archive:
    path:
      - "~/data/minecraft"
    dest: "~/data/backups/minecraft-{{ ansible_facts.date_time.date + '-' + ansible_facts.date_time.hour + '-' + ansible_facts.date_time.minute + '-' + ansible_facts.date_time.second }}.zip"
    format: zip

- name: "Backup - Minecraft - Start"
  containers.podman.podman_container:
    name: minecraft
    state: started
