---
matte:
  children:
    arcadiamc:
      hosts:
        rainbow.devices.waren.io:
      vars:
        ansible_user: wxl62975
        ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new -o LogLevel=error"
